from workflow import build_workflow


def main():

    workflow = build_workflow()

    # Security event generated by MQTT Flood / DoS detection
    security_event = {

    "alert_id": "ALERT-002",

    "topic": "/factory/sensor",

    "attack": "Normal Traffic",

    "total_messages": 20,

    "unique_payloads": 18,

    "duplicate_ratio": 0.10,

    "message_frequency": 2.0,

    "topic_frequency": 2.0,

    "payload_length": 15,

    "time_interval": 0.5,

    "severity": "LOW"
}

    print("=" * 60)
    print("        AGENTSEC-MQTT MULTI-AGENT TEST")
    print("=" * 60)

    print()
    print("Sending security event to LangGraph...")

    result = workflow.invoke(
        security_event
    )

    print()
    print("=" * 60)
    print("             AGENT RESULTS")
    print("=" * 60)

    print()

    print("MQTT Agent:")

    for finding in result.get(
        "mqtt_findings",
        []
    ):

        print(f"  ✓ {finding}")

    print()

    print("Log Agent:")

    for finding in result.get(
        "log_findings",
        []
    ):

        print(f"  ✓ {finding}")

    print()

    print("ML Agent:")

    for finding in result.get(
        "ml_findings",
        []
    ):

        print(f"  ✓ {finding}")

    print()
    print("=" * 60)


if __name__ == "__main__":

    main()